version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always 

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      - backend
    restart: always  
