# .github/workflows/deploy.yml
name: Deploy to DockerHub

on:
  push:
    branches:
      - main  # or your deployment branch
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Run tests
      run: pytest tests

    - name: Log in to DockerHub
      run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Build backend image
      run: docker build -t $DOCKERHUB_USERNAME/youtube_qa_backend:latest -f backend.Dockerfile .

    - name: Build frontend image
      run: docker build -t $DOCKERHUB_USERNAME/youtube_qa_frontend:latest -f frontend.Dockerfile .

    - name: Push backend image
      run: docker push $DOCKERHUB_USERNAME/youtube_qa_backend:latest

    - name: Push frontend image
      run: docker push $DOCKERHUB_USERNAME/youtube_qa_frontend:latest
